services:
  app:
    image: app
    build: .
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/db?user=app&password=pass
    ports:
      - '8080:8080'
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    name: postgres
    external: true
